TRAINING_MODEL_FILEPATH = 'model.pkl'

# yelp oauth
API_HOST = 'api.yelp.com'
CONSUMER_KEY = 'h47-HL9YY2_CsG2ROczy1w'
CONSUMER_SECRET = 'ijTRHMle0Qj-8ME8qKWEap_9thA'
TOKEN = 'BAWA8bXq7Aix-JwxJEBXXuT3KbH4g32I'
TOKEN_SECRET = '5RrUCbSQ52uihSs0-tF8Aq0zDxE'
